version: "3.7"
services:
  app:
    build:
      args:
        user: joselito
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pepe_laravel_image
    container_name: pepe_laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - red_chistosa
  db:
    image: mysql:8.0
    container_name: pepe_laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - red_chistosa
  nginx:
    image: nginx:alpine
    container_name: pepe_laravel_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - red_chistosa
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY 
    networks:
      - red_chistosa
networks:
  red_chistosa:
    driver: bridge

# Mirar de separ las redes, hay que intentar aislarlos entre si